name: Publish package to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS v12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
